name: Build Dropbear
run-name: ${{ github.actor }} is building dropbear on GitHub
on: [push]
jobs:
  Build-Dropbear:
    runs-on: ubuntu-latest
    container:
      image: alpine:3.22
    steps:
      - run: echo "?? The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "?? This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "?? The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v6
        run: |
          ls ${{ github.workspace }}
      - run: sh ./make-dropbear.sh bin/dropbear
      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: dropbear
          path: bin/dropbear
          archive: false

# TODO: Make a 'release' version which publishes the file as a release.
