name: Build Dropbear
run-name: ${{ github.actor }} is building dropbear on GitHub
on: [push]
#    paths:
#      - './make-dropbear.sh'
#      - './.github/workflows/dropbear.yml'
jobs:
  Build-Dropbear:
    runs-on: ubuntu-latest
    container:
      image: alpine:3.22
    steps:
      - run: echo "Job running on ${{ runner.os }} because ${{ github.event_name }} event from ${{ github.repository }} at ${{ github.ref }}"
      - name: Check out repository code
        uses: actions/checkout@v6
      - run: sh ./make-dropbear.sh ..
      - name: Upload distributions
        uses: actions/upload-artifact@v7
        with:
          name: dropbear
          path: dropbear
          archive: false

# TODO: Make a 'release' version which publishes the file as a release.
